name: Generate coverage report

on:
  workflow_dispatch:

  push:


permissions:
  contents: read
  actions: read
  checks: write
  pages: write
  id-token: write

jobs:
  build-test:
    env:
      java-version: "21"
      java-distribution: "temurin"
      min-coverage-overall: 80
      packages-user-name: "lucemonet"
      pass-emoji: "✔️"

      fail-emoji: "🥺"

      maven-settings-file-path: "settings.xml"
      working-directory: "."
    environment:
      name: github-pages-deploy
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
        shell: bash

    steps:
      - if: ${{ env.timezone != '' }}
        name: Set timezone to ${{ env.timezone }}
        run: |
          sudo timedatectl set-timezone ${{ env.timezone }}

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-distribution }}
          cache: "maven"

      - name: Build & Run Tests
        env:
          PACKAGES_USER_NAME: ${{ env.packages-user-name }}
          PACKAGES_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings ${{ env.maven-settings-file-path }} clean verify --no-transfer-progress

      - name: Makey JaCoCo Report
        uses: madrapps/jacoco-report@v1.7.1 # v1.6.1
        if: success()
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 🤖 Java Code Coverage
          min-coverage-overall: ${{ env.min-coverage-overall }}
          update-comment: ${{ env.update-comment }}
          pass-emoji: ${{ env.pass-emoji }}
          fail-emoji: ${{ env.fail-emoji }}
          debug-mode: 'true'
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
            jacoco-csv-file: target/site/jacoco/jacoco.csv
            badges-directory: target/site/jacoco/

      - name: Package relevant files
        run: |
          pwd
          mkdir results
      
          cp -R ${{ github.workspace }}/target/site/jacoco/* ./results
          echo " results contains:"
          ls -la  results/

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: "./results"

  # Publish to GH pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Deploy Test Report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4